//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidPay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPCard()
        {
            this.RPPayments = new HashSet<RPPayment>();
        }
    
        public string CardNumber { get; set; }
        public decimal Balance { get; set; }
        public decimal CreditLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPPayment> RPPayments { get; set; }
    }
}
